rbac:
  create: true

image:
  repository: localhost/metacontroller
  pullPolicy: IfNotPresent
  tag: "debug"

imagePullSecrets: []
nameOverride: ""
namespaceOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}

  name: ""

podAnnotations: {}

podSecurityContext: {}


securityContext: {}
 

resources: {}


nodeSelector: {}

tolerations: []

affinity: {}

command: "/dlv"


commandArgs:
  - --listen=:40000
  - --headless=true
  - --api-version=2
  - --continue            
  - --accept-multiclient  
  - exec
  - /usr/bin/metacontroller
  - --
  - --zap-log-level=4
  - --discovery-interval=20s
  - --zap-devel=true


priorityClassName: ""

clusterRole:
  aggregationRule: {}
  rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"

replicas: 1


podDisruptionBudget: {}
