rbac:
  create: true

image:
  repository: localhost/metacontroller
  pullPolicy: IfNotPresent
  tag: "dev"

imagePullSecrets: []
nameOverride: ""
namespaceOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
 
  name: ""

podAnnotations: {}

podSecurityContext: {}


securityContext: {}


resources: {}
 

nodeSelector: {}

tolerations: []

affinity: {}

command: "/usr/bin/metacontroller"


commandArgs:
  - --zap-log-level=4
  - --discovery-interval=20s
  - --cache-flush-interval=30m


priorityClassName: ""

clusterRole:
  aggregationRule: {}
  rules:
  - apiGroups:
      - "apps"
    resources:
      - "statefulsets"
    verbs:
      - "get"
      - "watch"
      - "list"
  - apiGroups:
      - ""
    resources:
      - "services"
    verbs:
      - "get"
      - "watch"
      - "list"
      - "create"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "create"
      - "patch"
  - apiGroups:
      - "metacontroller.k8s.io"
    resources:
      - "*"
    verbs:
      - "get"
      - "watch"
      - "list"

replicas: 1


podDisruptionBudget: {}

